package com.briup.apps.tb_app01.bean;

public class Phone {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_phone.id
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_phone.name
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_phone.price
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_phone.sales
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    private Long sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_phone.status
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_phone.id
     *
     * @return the value of tbl_phone.id
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_phone.id
     *
     * @param id the value for tbl_phone.id
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_phone.name
     *
     * @return the value of tbl_phone.name
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_phone.name
     *
     * @param name the value for tbl_phone.name
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_phone.price
     *
     * @return the value of tbl_phone.price
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_phone.price
     *
     * @param price the value for tbl_phone.price
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_phone.sales
     *
     * @return the value of tbl_phone.sales
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public Long getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_phone.sales
     *
     * @param sales the value for tbl_phone.sales
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public void setSales(Long sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_phone.status
     *
     * @return the value of tbl_phone.status
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_phone.status
     *
     * @param status the value for tbl_phone.status
     *
     * @mbg.generated Tue Apr 30 15:14:24 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}